domain    = "clutter_ml/clutter.pddl"
problem   = "clutter_ml/clutter_prob0.pddl"
scene     = "clutter_ml/clutter_prob0.xml"
objdir    = "clutter_ml/"
semantics = "clutter_ml.lua"
output    = "clutter_ml_solution.json"
perf_file = "clutter_ml.csv"
params    = "params.toml"
blacklist = "models/pr2_collision_blacklist.csv"
cont_state_file = "clutter_ml_cont_state.txt"
disc_state_file = "clutter_ml_disc_state.txt"
time_file = "cultter_ml_time.txt"
cfg_file = "clutter_ml_cfg.txt"